name = "og-composite-worker"
main = "index.ts"
account_id = "d2a602a0ca085abb9803701d0c554d79"
workers_dev = true
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["index_bg.wasm"]
fallthrough = true

[vars]
DEBUG = "true"